server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/zero1814/spring-cloud-study/
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: config-repo
          # git仓库的账号
          username: zero1814
          # git仓库的密码
          password: yad1ano622